import * as ts from 'typescript';

function debugNodeRecur(node: ts.Node, indent: number): void {
  const indentString = new Array(indent).join('  ');
  // tslint:disable-next-line:no-console
  console.log(`${indentString}${SyntaxKindToString[node.kind]} => ${node.getText()}`);
  node.getChildren().forEach(n => debugNodeRecur(n, indent + 1));
}

export function debugNode(node: ts.Node): void {
  debugNodeRecur(node, 0);
}

export const SyntaxKindToString = {
  0: 'FirstToken | Unknown',
  1: 'EndOfFileToken',
  10: 'JsxText',
  100: 'ThrowKeyword',
  101: 'TrueKeyword',
  102: 'TryKeyword',
  103: 'TypeOfKeyword',
  104: 'VarKeyword',
  105: 'VoidKeyword',
  106: 'WhileKeyword',
  107: 'LastReservedWord | WithKeyword',
  108: 'FirstFutureReservedWord | ImplementsKeyword',
  109: 'InterfaceKeyword',
  11: 'JsxTextAllWhiteSpaces',
  110: 'LetKeyword',
  111: 'PackageKeyword',
  112: 'PrivateKeyword',
  113: 'ProtectedKeyword',
  114: 'PublicKeyword',
  115: 'StaticKeyword',
  116: 'LastFutureReservedWord | YieldKeyword',
  117: 'AbstractKeyword',
  118: 'AsKeyword',
  119: 'AnyKeyword',
  12: 'RegularExpressionLiteral',
  120: 'AsyncKeyword',
  121: 'AwaitKeyword',
  122: 'BooleanKeyword',
  123: 'ConstructorKeyword',
  124: 'DeclareKeyword',
  125: 'GetKeyword',
  126: 'InferKeyword',
  127: 'IsKeyword',
  128: 'KeyOfKeyword',
  129: 'ModuleKeyword',
  13: 'FirstTemplateToken | LastLiteralToken | NoSubstitutionTemplateLiteral',
  130: 'NamespaceKeyword',
  131: 'NeverKeyword',
  132: 'ReadonlyKeyword',
  133: 'RequireKeyword',
  134: 'NumberKeyword',
  135: 'ObjectKeyword',
  136: 'SetKeyword',
  137: 'StringKeyword',
  138: 'SymbolKeyword',
  139: 'TypeKeyword',
  14: 'TemplateHead',
  140: 'UndefinedKeyword',
  141: 'UniqueKeyword',
  142: 'UnknownKeyword',
  143: 'FromKeyword',
  144: 'GlobalKeyword',
  145: 'LastKeyword | LastToken | OfKeyword',
  146: 'FirstNode | QualifiedName',
  147: 'ComputedPropertyName',
  148: 'TypeParameter',
  149: 'Parameter',
  15: 'TemplateMiddle',
  150: 'Decorator',
  151: 'PropertySignature',
  152: 'PropertyDeclaration',
  153: 'MethodSignature',
  154: 'MethodDeclaration',
  155: 'Constructor',
  156: 'GetAccessor',
  157: 'SetAccessor',
  158: 'CallSignature',
  159: 'ConstructSignature',
  16: 'LastTemplateToken | TemplateTail',
  160: 'IndexSignature',
  161: 'FirstTypeNode | TypePredicate',
  162: 'TypeReference',
  163: 'FunctionType',
  164: 'ConstructorType',
  165: 'TypeQuery',
  166: 'TypeLiteral',
  167: 'ArrayType',
  168: 'TupleType',
  169: 'OptionalType',
  17: 'FirstPunctuation | OpenBraceToken',
  170: 'RestType',
  171: 'UnionType',
  172: 'IntersectionType',
  173: 'ConditionalType',
  174: 'InferType',
  175: 'ParenthesizedType',
  176: 'ThisType',
  177: 'TypeOperator',
  178: 'IndexedAccessType',
  179: 'MappedType',
  18: 'CloseBraceToken',
  180: 'LiteralType',
  181: 'ImportType | LastTypeNode',
  182: 'ObjectBindingPattern',
  183: 'ArrayBindingPattern',
  184: 'BindingElement',
  185: 'ArrayLiteralExpression',
  186: 'ObjectLiteralExpression',
  187: 'PropertyAccessExpression',
  188: 'ElementAccessExpression',
  189: 'CallExpression',
  19: 'OpenParenToken',
  190: 'NewExpression',
  191: 'TaggedTemplateExpression',
  192: 'TypeAssertionExpression',
  193: 'ParenthesizedExpression',
  194: 'FunctionExpression',
  195: 'ArrowFunction',
  196: 'DeleteExpression',
  197: 'TypeOfExpression',
  198: 'VoidExpression',
  199: 'AwaitExpression',
  2: 'FirstTriviaToken | SingleLineCommentTrivia',
  20: 'CloseParenToken',
  200: 'PrefixUnaryExpression',
  201: 'PostfixUnaryExpression',
  202: 'BinaryExpression',
  203: 'ConditionalExpression',
  204: 'TemplateExpression',
  205: 'YieldExpression',
  206: 'SpreadElement',
  207: 'ClassExpression',
  208: 'OmittedExpression',
  209: 'ExpressionWithTypeArguments',
  21: 'OpenBracketToken',
  210: 'AsExpression',
  211: 'NonNullExpression',
  212: 'MetaProperty',
  213: 'SyntheticExpression',
  214: 'TemplateSpan',
  215: 'SemicolonClassElement',
  216: 'Block',
  217: 'VariableStatement',
  218: 'EmptyStatement',
  219: 'ExpressionStatement',
  22: 'CloseBracketToken',
  220: 'IfStatement',
  221: 'DoStatement',
  222: 'WhileStatement',
  223: 'ForStatement',
  224: 'ForInStatement',
  225: 'ForOfStatement',
  226: 'ContinueStatement',
  227: 'BreakStatement',
  228: 'ReturnStatement',
  229: 'WithStatement',
  23: 'DotToken',
  230: 'SwitchStatement',
  231: 'LabeledStatement',
  232: 'ThrowStatement',
  233: 'TryStatement',
  234: 'DebuggerStatement',
  235: 'VariableDeclaration',
  236: 'VariableDeclarationList',
  237: 'FunctionDeclaration',
  238: 'ClassDeclaration',
  239: 'InterfaceDeclaration',
  24: 'DotDotDotToken',
  240: 'TypeAliasDeclaration',
  241: 'EnumDeclaration',
  242: 'ModuleDeclaration',
  243: 'ModuleBlock',
  244: 'CaseBlock',
  245: 'NamespaceExportDeclaration',
  246: 'ImportEqualsDeclaration',
  247: 'ImportDeclaration',
  248: 'ImportClause',
  249: 'NamespaceImport',
  25: 'SemicolonToken',
  250: 'NamedImports',
  251: 'ImportSpecifier',
  252: 'ExportAssignment',
  253: 'ExportDeclaration',
  254: 'NamedExports',
  255: 'ExportSpecifier',
  256: 'MissingDeclaration',
  257: 'ExternalModuleReference',
  258: 'JsxElement',
  259: 'JsxSelfClosingElement',
  26: 'CommaToken',
  260: 'JsxOpeningElement',
  261: 'JsxClosingElement',
  262: 'JsxFragment',
  263: 'JsxOpeningFragment',
  264: 'JsxClosingFragment',
  265: 'JsxAttribute',
  266: 'JsxAttributes',
  267: 'JsxSpreadAttribute',
  268: 'JsxExpression',
  269: 'CaseClause',
  27: 'FirstBinaryOperator | LessThanToken',
  270: 'DefaultClause',
  271: 'HeritageClause',
  272: 'CatchClause',
  273: 'PropertyAssignment',
  274: 'ShorthandPropertyAssignment',
  275: 'SpreadAssignment',
  276: 'EnumMember',
  277: 'SourceFile',
  278: 'Bundle',
  279: 'UnparsedSource',
  28: 'LessThanSlashToken',
  280: 'InputFiles',
  281: 'FirstJSDocNode | JSDocTypeExpression',
  282: 'JSDocAllType',
  283: 'JSDocUnknownType',
  284: 'JSDocNullableType',
  285: 'JSDocNonNullableType',
  286: 'JSDocOptionalType',
  287: 'JSDocFunctionType',
  288: 'JSDocVariadicType',
  289: 'JSDocComment',
  29: 'GreaterThanToken',
  290: 'JSDocTypeLiteral',
  291: 'JSDocSignature',
  292: 'FirstJSDocTagNode | JSDocTag',
  293: 'JSDocAugmentsTag',
  294: 'JSDocClassTag',
  295: 'JSDocCallbackTag',
  296: 'JSDocEnumTag',
  297: 'JSDocParameterTag',
  298: 'JSDocReturnTag',
  299: 'JSDocThisTag',
  3: 'MultiLineCommentTrivia',
  30: 'LessThanEqualsToken',
  300: 'JSDocTypeTag',
  301: 'JSDocTemplateTag',
  302: 'JSDocTypedefTag',
  303: 'JSDocPropertyTag | LastJSDocNode | LastJSDocTagNode',
  304: 'SyntaxList',
  305: 'NotEmittedStatement',
  306: 'PartiallyEmittedExpression',
  307: 'CommaListExpression',
  308: 'MergeDeclarationMarker',
  309: 'EndOfDeclarationMarker',
  31: 'GreaterThanEqualsToken',
  310: 'Count',
  32: 'EqualsEqualsToken',
  33: 'ExclamationEqualsToken',
  34: 'EqualsEqualsEqualsToken',
  35: 'ExclamationEqualsEqualsToken',
  36: 'EqualsGreaterThanToken',
  37: 'PlusToken',
  38: 'MinusToken',
  39: 'AsteriskToken',
  4: 'NewLineTrivia',
  40: 'AsteriskAsteriskToken',
  41: 'SlashToken',
  42: 'PercentToken',
  43: 'PlusPlusToken',
  44: 'MinusMinusToken',
  45: 'LessThanLessThanToken',
  46: 'GreaterThanGreaterThanToken',
  47: 'GreaterThanGreaterThanGreaterThanToken',
  48: 'AmpersandToken',
  49: 'BarToken',
  5: 'WhitespaceTrivia',
  50: 'CaretToken',
  51: 'ExclamationToken',
  52: 'TildeToken',
  53: 'AmpersandAmpersandToken',
  54: 'BarBarToken',
  55: 'QuestionToken',
  56: 'ColonToken',
  57: 'AtToken',
  58: 'EqualsToken | FirstAssignment',
  59: 'FirstCompoundAssignment | PlusEqualsToken',
  6: 'ShebangTrivia',
  60: 'MinusEqualsToken',
  61: 'AsteriskEqualsToken',
  62: 'AsteriskAsteriskEqualsToken',
  63: 'SlashEqualsToken',
  64: 'PercentEqualsToken',
  65: 'LessThanLessThanEqualsToken',
  66: 'GreaterThanGreaterThanEqualsToken',
  67: 'GreaterThanGreaterThanGreaterThanEqualsToken',
  68: 'AmpersandEqualsToken',
  69: 'BarEqualsToken',
  7: 'ConflictMarkerTrivia | LastTriviaToken',
  70: 'CaretEqualsToken | LastAssignment | LastBinaryOperator | LastCompoundAssignment | LastPunctuation',
  71: 'Identifier',
  72: 'BreakKeyword | FirstKeyword | FirstReservedWord',
  73: 'CaseKeyword',
  74: 'CatchKeyword',
  75: 'ClassKeyword',
  76: 'ConstKeyword',
  77: 'ContinueKeyword',
  78: 'DebuggerKeyword',
  79: 'DefaultKeyword',
  8: 'FirstLiteralToken | NumericLiteral',
  80: 'DeleteKeyword',
  81: 'DoKeyword',
  82: 'ElseKeyword',
  83: 'EnumKeyword',
  84: 'ExportKeyword',
  85: 'ExtendsKeyword',
  86: 'FalseKeyword',
  87: 'FinallyKeyword',
  88: 'ForKeyword',
  89: 'FunctionKeyword',
  9: 'StringLiteral',
  90: 'IfKeyword',
  91: 'ImportKeyword',
  92: 'InKeyword',
  93: 'InstanceOfKeyword',
  94: 'NewKeyword',
  95: 'NullKeyword',
  96: 'ReturnKeyword',
  97: 'SuperKeyword',
  98: 'SwitchKeyword',
  99: 'ThisKeyword',
};
