export const CAPACITE_MACHINE = 980;

export const MAX_SPEED_RATIO = 0.82;
export const MAX_SPEED = 180;

const ADDITIONAL_MINUTES_TO_RESTART_PROD = 20;
export const ADDITIONAL_TIME_TO_RESTART_PROD = ADDITIONAL_MINUTES_TO_RESTART_PROD * 60 * 1000;
